### ISSUE TITLE
issue 1 - sankey plot - not working properly (probably) if 3 levels and many items in 3 level 

### ISSUE THREAD

**Issue by ghost** [timelyportfolio/rCharts_d3_sankey#1]
![foo](https://f.cloud.github.com/assets/3903647/1005104/15a03da8-0ab1-11e3-93a2-db8fdbd43775.png)
Hi,

My data.frame:

> str(bbb)
> 'data.frame':   1116 obs. of  3 variables:
>  $ source: chr  "SVC_GTS" "SVC_TWR" "SVC_TWR" "SVC_GTS" ...
>  $ target: chr  "AMS_GTS_SAS600" "AMS_TWR_SAS600" "DS5K_TWR_FC300" "DS5K_GTS_FC300" ...
>  $ value : num  0.99 1 0.84 1 0.97 0.97 0.08 0.06 0.44 0.44 ...

I do :
library(rCharts)
library(lattice)
sankeyPlot <- rCharts$new()
sankeyPlot$setLib('../rCharts_d3_sankey')
sankeyPlot$setTemplate(script = "../rCharts_d3_sankey/layouts/chart.html")
require(devtools)
install_github('rCharts', 'ramnathv')
sankeyPlot$set(
  data = bbb,
  nodeWidth = 15,
  nodePadding = 10,
  layout = 32,
  width = 750,
  height = 500,
  labelFormat = ".1%"
)
sankeyPlot

Picture and data.frame bbb attached to post ( change foo.PNG to foo.ZIP)
![screen shot 2013-08-22 at 12 32 35 am](https://f.cloud.github.com/assets/3903647/1005129/a321cd22-0ab1-11e3-8b72-be3f30c16ab3.png)

Thank you in advance.

Best regards
robert

**Comment by timelyportfolio** [comment]
I am aware of this limitation and unfortunately I have not found a good solution besides the unacceptable massive height parameter specification.  So far, I have decided the Sankey might not be good for this number of levels.  Let me know if you make any discoveries.  Thanks for trying and using.
