### ISSUE TITLE
Error in yaml.load(paste(readLines(input), collapse = "\n"), ...)

### ISSUE THREAD

**Issue by calang** [timelyportfolio/rCharts_d3_sankey#8]
After downloading the files and adjusting the paths in the way I think is necessary, I get the following error message:
Error in yaml.load(paste(readLines(input), collapse = "\n"), ...) : 
  Scanner error: mapping values are not allowed in this context

Is it something obvious that I can fix?

My current code follows.
-.-.-.-.-.-
require(rCharts)
require(rjson)
# Note:
# https://github.com/ramnathv/rCharts/issues/515
# get source from original example
# this is a JSON, so will need to translate
# this is complicated and unnecessary but feel I need to replicate
# for completeness
# expect most data to come straight from R
# in form of source, target, value

links <- matrix(unlist(
    rjson::fromJSON(
        # file = "http://bost.ocks.org/mike/sankey/energy.json"
        file = "input/energy.json"
    )$links
),ncol = 3, byrow = TRUE)
nodes <- unlist(
    rjson::fromJSON(
        # file = "http://bost.ocks.org/mike/sankey/energy.json"
        file = "input/energy.json"
    )$nodes
)
# convert to data.frame so souce and target can be character and value numeric

links <- data.frame(links)
colnames(links) <- c("source", "target", "value")
links$source <- sapply(links$source, FUN = function(x) {return(as.character(nodes[x+1]))}) #x+1 since js starts at 0
links$target <- sapply(links$target, FUN = function(x) {return(nodes[x+1])}) #x+1 since js starts at 0
# now we finally have the data in the form we need

sankeyPlot <- rCharts$new()
sankeyPlot$setLib('d3_sankey')
sankeyPlot$setTemplate(script = "d3_sankey/layouts/chart.html")
sankeyPlot$set(
    data = links,
    nodeWidth = 15,
    nodePadding = 10,
    layout = 32,
    width = 960,
    height = 500,
    units = "TWh",
    title = "Sankey Diagram"
)
sankeyPlot
-.-.-.-.-.-
I downloaded the contents of this folder in a "d3_sankey" directory in the working dir, and also downloaded the json data file, as an additional earlier simplification.
Any suggestions?
Thanks.

**Comment by timelyportfolio** [comment]
Maybe #3 will help.  You can try to change

```
sankeyPlot$setLib("http://timelyportfolio.github.io/rCharts_d3_sankey")
#needed to satisfy dev branch and avoid an error
sankeyPlot$setTemplate(
  afterScript = "<script></script>"
)
```

Let me know.  Also you might want to try [`networkD3`](https://github.com/christophergandrud/networkD3).

**Comment by calang** [comment]
Sorry for not coming back until now ... hectic week!

Actually i did download a whole copy of the rCharts_d3_sankey directory and pointed sankeyPlot$setLib to it.
That was enough for it to work.  thanks anyway.

I did take a quick look at networkd3; will surely give it a try!  :)

**Comment by perfectatdat** [comment]
I am getting the same error. The fix that you have mentioned about adding the setTemplate() does not work.
      sankeyPlot$setTemplate(
          afterScript = "<script></script>"
      )
